shopgate/theme-gmd

locale/de-DE.json, locale/en-US.json
- moved the countdown locale string out of the liveshopping scope into a common scope
=> CON-2374: Moved the countdown format string from the liveshopping field to the common field, inside the locale

components/Navigator/actions/toggleCartIcon.js, components/Navigator/components/CartButton/connector.js, components/Navigator/selectors/index.js
- moved it from pwa-common-commerce to theme-gmd
- adjusted the imports
- removed unused isCartLoading selector
=> CON-2383: moved the isCartButtonVisible selector

components/FilterBar/index.jsx, components/FilterBar/style.js, components/View/index.jsx
The FilterBar is now shown/hidden at the correct time.
=> CON-2375 A viewRef prop is now passed to the children of the View component

components/NoResults/index.jsx, components/View/index.jsx, pages/Category/components/Empty/connector.js, pages/Category/components/Empty/index.jsx, pages/Category/components/Empty/selectors.js
Children of the View component now only receive the viewRef prop if they are actually React components.
=> CON-2439 Empty component now displays on a Category route with no content

components/Dialog/index.jsx
- setted TestMessageDialog component as default, when a message, but no
type is passed through the params
=> CON-2622: changed DialogComponent type handling

components/CategoryList/connector.js, npm-shrinkwrap.json, pages/Category/connector.js
- replaced the routed connect helper by the original redux connect
=> CON-2558 Fixed broken category lists on back navigation

widgets/Html/index.jsx, widgets/Html/style.js
- removed touchStart event listener from links
- added clearfix to avoid display issues at sibling widgets
=> CON-2368: HTML widget bugfixes

pages/index.jsx
Removed duplicated import.
Fixed code style.
=> Duplicated import.

components/Viewport/style.js, pages/Product/components/Description/__snapshots__/spec.jsx.snap, pages/Product/components/Description/style.js, styles/index.js
- the user now can't trigger the text selection tool anymore by long pressing at text elements
=> PI-8206: Deactivated text selection globally

extension-config.json
- add product properties filter (whitelist/blacklist) feature flag
=> CON-2842: Only whitelisted properties are shown on product pages

components/View/index.jsx
=> PI-8460: Broken meta-title

components/ContextMenu/index.jsx, components/ImageSlider/index.jsx, components/ProductCard/index.jsx, components/ProductGrid/components/Item/index.jsx, components/ProductList/components/Item/index.jsx, components/Reviews/components/AllReviewsLink/index.jsx, pages/Cart/components/Item/components/Product/index.jsx, pages/Product/actions/getProductData.js, pages/Product/components/VariantSelects/components/ProductVariants/__snapshots__/spec.jsx.snap, pages/Product/components/VariantSelects/components/ProductVariants/index.jsx, pages/Product/components/VariantSelects/components/ProductVariants/spec.jsx, pages/Product/components/VariantSelects/connector.js, pages/Product/subscriptions.js, widgets/Liveshopping/index.jsx
Reverts shopgate/theme-gmd#158
=> Revert "CON-2003 open products from cart"

components/ContextMenu/index.jsx, components/ImageSlider/index.jsx, components/ProductCard/index.jsx, components/ProductGrid/components/Item/index.jsx, components/ProductList/components/Item/index.jsx, components/Reviews/components/AllReviewsLink/index.jsx, pages/Cart/components/Item/components/Product/index.jsx, pages/Product/actions/getProductData.js, pages/Product/components/VariantSelects/components/ProductVariants/__snapshots__/spec.jsx.snap, pages/Product/components/VariantSelects/components/ProductVariants/index.jsx, pages/Product/components/VariantSelects/components/ProductVariants/spec.jsx, pages/Product/components/VariantSelects/connector.js, pages/Product/subscriptions.js, widgets/Liveshopping/index.jsx
Reverts shopgate/theme-gmd#160
=> Revert "Revert "CON-2003 open products from cart""

widgets/Liveshopping/__snapshots__/spec.jsx.snap, widgets/Liveshopping/index.jsx, widgets/Liveshopping/spec.jsx, widgets/Liveshopping/style.js
- fix liveshopping widgets styling and tests
(cherry picked from commit ea46ac8)
=> PI-8510: Liveshopping widget styling

components/ProductCard/index.jsx, widgets/Liveshopping/index.jsx
- Liveshopping widget
- ProductCard
=> PWA-119: Added DiscountBadge portals to more components

pages/Filter/__snapshots__/spec.jsx.snap, pages/Filter/index.jsx, pages/Filter/mock.js, pages/Filter/spec.jsx
=> PWA-218: Add portals to prices on category page

locale/index.js
- now matches the method signature of the helper module within common
=> PWA-293: Updated the parameter order of the mergeTranslations call

components/Viewport/style.js
- on iOS the page background isn't black anymore while route based bundles are loaded
=> CCP-646: Added background color to the pages

pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/__snapshots__/spec.jsx.snap, pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/index.jsx
- now the button looks disabled agein when the checkout is not possible
=> PWA-612: Fix to disable the checkout button visually

components/ChipLayout/__snapshots__/spec.jsx.snap, components/ChipLayout/index.jsx, components/ChipLayout/style.js, components/FilterBar/__snapshots__/spec.jsx.snap, components/FilterBar/components/Content/components/FilterChips/__snapshots__/spec.jsx.snap, components/FilterBar/components/Content/components/FilterChips/connector.js, components/FilterBar/components/Content/components/FilterChips/index.jsx, pages/Filter/__snapshots__/spec.jsx.snap, pages/Filter/components/ListItem/components/CrossButton/style.js, pages/Filter/components/ListItem/style.js, pages/FilterAttribute/connector.js
- correct max-height for filter chips wrapper
- filter chips "more" button visibility is evaluated more often
=> PWA-252 - fixes for the filter chips

pages/Product/components/Header/index.jsx
- took care that the manufacturer name is always picked from the current selected product
=> PWA-809: Fixed displaying of the manufacturer name

components/Reviews/components/Header/__snapshots__/spec.jsx.snap, components/Reviews/components/Header/index.jsx, components/Reviews/components/Header/spec.jsx, pages/WriteReview/subscriptions.spec.js
- the write review form is now opened for the product id of the parent product
- updated unit tests
=> PWA-816: Fix for the write review button

components/ProductGrid/components/Item/connector.js, components/Reviews/components/Header/components/AverageRating/connector.js, components/Reviews/components/Header/spec.jsx, pages/Product/components/Content/__snapshots__/spec.jsx.snap, pages/Product/components/Content/connector.js, pages/Product/components/Content/index.jsx, pages/Product/components/Header/components/CTAButtons/components/CartButton/connector.js, pages/Product/components/Header/components/CTAButtons/components/CartButton/index.jsx, pages/WriteReview/components/ReviewForm/__snapshots__/spec.jsx.snap, pages/WriteReview/components/ReviewForm/connector.js, pages/WriteReview/components/ReviewForm/spec.jsx, pages/WriteReview/mock.js
- updated product selectors to the new invocation pattern where necessary
- fixed affected components and tests
=> PWA-860: Implemented updated product selectors

locale/it-IT.json
https://jira.shopgate.guru/browse/CCP-802
=> Added Italian translation

locale/es-ES.json
https://jira.shopgate.guru/browse/CCP-801
=> Added Spanish translation
